version: "3.8"

networks:
  legal-ai-network:  # Define a common network

services:
  api_gateway:
    build: ./api_gateway
    ports:
      - "8000:8000"
    depends_on:
      - ocr_service
      - vector_database_service
      - legal_clause_validator
    env_file:
      - .env
    networks:
      - legal-ai-network  # Attach to the network

  ocr_service:
    build: ./ocr_service
    ports:
      - "8001:8001"
    env_file:
      - .env
    networks:
      - legal-ai-network

  vector_database_service:
    build: ./vector_database_service
    ports:
      - "8002:8002"
    env_file:
      - .env
    networks:
      - legal-ai-network

  legal_clause_validator:
    build: ./legal_clause_validator
    ports:
      - "8003:8003"
    env_file:
      - .env
    networks:
      - legal-ai-network
